### PR TITLE
Created a gcc Makefile and made project compile under Ubuntu

### PR DESCRIPTION
**Pull request by ratsept**
Hey,

I took your work and made it compile under Ubuntu. Also added a bunch of debugging but you can remove that if you don't need it. Never really tried this Pull Request feature before so sorry if I'm doing something wrong. Just wanted to give you back my changes. Thanks for the effort man :)

### CODE REVIEW

**Comment by jmoyerman** [comment]
I see that you've also turned off the SSL connection, did you try to get that to work, or just decide to go unsecured?
I appreciate the help, and want to get this merged in soon. How do you flash the binary to the board once compiled on linux? I recall uniflash being windows only.

**Comment by ratsept** [comment]
I turned off the SSL just because I didn't flash the board yet. I think
(reading from TI forums) that it should be possible with a tool from the
Energia IDE suite but I'm still working on this. I'm not exactly sure if
that tool can be used to flash the cert needed too and that's why I'm not
using SSL at the moment. I'm sure it'll work with the encypted connection
too but I may need to add a bit of stuff to the Makefile to get a real bin
file. Debugging with GDB at the moment.

On Mon, Oct 20, 2014 at 7:33 PM, joshua-moyerman notifications@github.com
wrote:

> I see that you've also turned off the SSL connection, did you try to get
> that to work, or just decide to go unsecured?
> I appreciate the help, and want to get this merged in soon. How do you
> flash the binary to the board once compiled on linux? I recall uniflash
> being windows only.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/stellascapes/mqtt-examples/pull/1#issuecomment-59793966
> .

## 

Tiit Rätsep
Wazombi Labs OÜ
skype: ratsept
+372 5532260

**Comment by ratsept** [comment]
It seems that I can flash the binary with the tool from the Energia package
(cc3200prog) but I can't use that to write the cert into the flash. So I'm
getting error SL_ESECBADCAFILE and I think this means that it can't find
the file. So I could either write a tool to flash certs to the board or
much more likely I will just program the flash chips on my own boards in
production using my own hardware and not spend too much time on this.

I have a question too. Why haven't you made a separate task for the buttons
and make that publish to another topic? I think I will change the
publishing scheme a bit so that it looks more like what MQTT is aiming for.
Feel free to ignore these changes as they reflect my personal understanding
of how it should be done. I will try and change it so that there will be a
topic "ticc3200" but that will have subtopics "ticc3200/leds/red",
ticc3200/leds/yellow", ticc3200/leds/green" and publish "on" and "off"
there (or 1 and 0, or H and L whatever). I will also make topics for the
buttons and make them "push" msgs to their respective topics.

On Mon, Oct 20, 2014 at 7:36 PM, Tiit Rätsep ratsept@gmail.com wrote:

> I turned off the SSL just because I didn't flash the board yet. I think
> (reading from TI forums) that it should be possible with a tool from the
> Energia IDE suite but I'm still working on this. I'm not exactly sure if
> that tool can be used to flash the cert needed too and that's why I'm not
> using SSL at the moment. I'm sure it'll work with the encypted connection
> too but I may need to add a bit of stuff to the Makefile to get a real bin
> file. Debugging with GDB at the moment.
> 
> On Mon, Oct 20, 2014 at 7:33 PM, joshua-moyerman <notifications@github.com
> 
> > wrote:
> > 
> > I see that you've also turned off the SSL connection, did you try to get
> > that to work, or just decide to go unsecured?
> > I appreciate the help, and want to get this merged in soon. How do you
> > flash the binary to the board once compiled on linux? I recall uniflash
> > being windows only.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/stellascapes/mqtt-examples/pull/1#issuecomment-59793966
> > .
> 
> ## 
> 
> Tiit Rätsep
> Wazombi Labs OÜ
> skype: ratsept
> +372 5532260

## 

Tiit Rätsep
Wazombi Labs OÜ
skype: ratsept
+372 5532260

**Comment by ratsept** [comment]
Ok ... now I found a really bad problem.

It seems that the paho project MQTT implementation for CC3200 with FreeRTOS
is broken. Or more specifically it breaks the task scheduler in FreeRTOS by
configuring the SysTick interrupt incorrectly. It seems that FreeRTOS wants
mostly exclusive control over that interrupt to schedule it's tasks. So
paho using it for timing is breaking everything. The reason this seems to
work for your example is that your code runs in a single thread after the
network is initialized. I'm not sure where to report this bug but I will
try to fix it for my own use first. This seems to be a problem with the
paho port for CC3200 and doesn't require a change in your code - I just
wanted to let you guys know about this.

On Mon, Oct 20, 2014 at 9:13 PM, Tiit Rätsep ratsept@gmail.com wrote:

> It seems that I can flash the binary with the tool from the Energia
> package (cc3200prog) but I can't use that to write the cert into the flash.
> So I'm getting error SL_ESECBADCAFILE and I think this means that it can't
> find the file. So I could either write a tool to flash certs to the board
> or much more likely I will just program the flash chips on my own boards in
> production using my own hardware and not spend too much time on this.
> 
> I have a question too. Why haven't you made a separate task for the
> buttons and make that publish to another topic? I think I will change the
> publishing scheme a bit so that it looks more like what MQTT is aiming for.
> Feel free to ignore these changes as they reflect my personal understanding
> of how it should be done. I will try and change it so that there will be a
> topic "ticc3200" but that will have subtopics "ticc3200/leds/red",
> ticc3200/leds/yellow", ticc3200/leds/green" and publish "on" and "off"
> there (or 1 and 0, or H and L whatever). I will also make topics for the
> buttons and make them "push" msgs to their respective topics.
> 
> On Mon, Oct 20, 2014 at 7:36 PM, Tiit Rätsep ratsept@gmail.com wrote:
> 
> > I turned off the SSL just because I didn't flash the board yet. I think
> > (reading from TI forums) that it should be possible with a tool from the
> > Energia IDE suite but I'm still working on this. I'm not exactly sure if
> > that tool can be used to flash the cert needed too and that's why I'm not
> > using SSL at the moment. I'm sure it'll work with the encypted connection
> > too but I may need to add a bit of stuff to the Makefile to get a real bin
> > file. Debugging with GDB at the moment.
> > 
> > On Mon, Oct 20, 2014 at 7:33 PM, joshua-moyerman <
> > notifications@github.com> wrote:
> > 
> > > I see that you've also turned off the SSL connection, did you try to get
> > > that to work, or just decide to go unsecured?
> > > I appreciate the help, and want to get this merged in soon. How do you
> > > flash the binary to the board once compiled on linux? I recall uniflash
> > > being windows only.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/stellascapes/mqtt-examples/pull/1#issuecomment-59793966
> > > .
> > 
> > ## 
> > 
> > Tiit Rätsep
> > Wazombi Labs OÜ
> > skype: ratsept
> > +372 5532260
> 
> ## 
> 
> Tiit Rätsep
> Wazombi Labs OÜ
> skype: ratsept
> +372 5532260

## 

Tiit Rätsep
Wazombi Labs OÜ
skype: ratsept
+372 5532260

**Comment by ratsept** [comment]
I have raised this as a bug in paho repository and I fixed it for my own
use but since my fix would break backwards compatibility I won't commit
anything there for the moment. I did push the changed paho files to my own
repo and I now have a code that listens to led notifications in one thread
and publishes button notifications in another thread - both threads have
their own connection to the server.

On Tue, Oct 21, 2014 at 12:43 PM, Tiit Rätsep ratsept@gmail.com wrote:

> Ok ... now I found a really bad problem.
> 
> It seems that the paho project MQTT implementation for CC3200 with
> FreeRTOS is broken. Or more specifically it breaks the task scheduler in
> FreeRTOS by configuring the SysTick interrupt incorrectly. It seems that
> FreeRTOS wants mostly exclusive control over that interrupt to schedule
> it's tasks. So paho using it for timing is breaking everything. The reason
> this seems to work for your example is that your code runs in a single
> thread after the network is initialized. I'm not sure where to report this
> bug but I will try to fix it for my own use first. This seems to be a
> problem with the paho port for CC3200 and doesn't require a change in your
> code - I just wanted to let you guys know about this.
> 
> On Mon, Oct 20, 2014 at 9:13 PM, Tiit Rätsep ratsept@gmail.com wrote:
> 
> > It seems that I can flash the binary with the tool from the Energia
> > package (cc3200prog) but I can't use that to write the cert into the flash.
> > So I'm getting error SL_ESECBADCAFILE and I think this means that it can't
> > find the file. So I could either write a tool to flash certs to the board
> > or much more likely I will just program the flash chips on my own boards in
> > production using my own hardware and not spend too much time on this.
> > 
> > I have a question too. Why haven't you made a separate task for the
> > buttons and make that publish to another topic? I think I will change the
> > publishing scheme a bit so that it looks more like what MQTT is aiming for.
> > Feel free to ignore these changes as they reflect my personal understanding
> > of how it should be done. I will try and change it so that there will be a
> > topic "ticc3200" but that will have subtopics "ticc3200/leds/red",
> > ticc3200/leds/yellow", ticc3200/leds/green" and publish "on" and "off"
> > there (or 1 and 0, or H and L whatever). I will also make topics for the
> > buttons and make them "push" msgs to their respective topics.
> > 
> > On Mon, Oct 20, 2014 at 7:36 PM, Tiit Rätsep ratsept@gmail.com wrote:
> > 
> > > I turned off the SSL just because I didn't flash the board yet. I think
> > > (reading from TI forums) that it should be possible with a tool from the
> > > Energia IDE suite but I'm still working on this. I'm not exactly sure if
> > > that tool can be used to flash the cert needed too and that's why I'm not
> > > using SSL at the moment. I'm sure it'll work with the encypted connection
> > > too but I may need to add a bit of stuff to the Makefile to get a real bin
> > > file. Debugging with GDB at the moment.
> > > 
> > > On Mon, Oct 20, 2014 at 7:33 PM, joshua-moyerman <
> > > notifications@github.com> wrote:
> > > 
> > > > I see that you've also turned off the SSL connection, did you try to
> > > > get that to work, or just decide to go unsecured?
> > > > I appreciate the help, and want to get this merged in soon. How do you
> > > > flash the binary to the board once compiled on linux? I recall uniflash
> > > > being windows only.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/stellascapes/mqtt-examples/pull/1#issuecomment-59793966
> > > > .
> > > 
> > > ## 
> > > 
> > > Tiit Rätsep
> > > Wazombi Labs OÜ
> > > skype: ratsept
> > > +372 5532260
> > 
> > ## 
> > 
> > Tiit Rätsep
> > Wazombi Labs OÜ
> > skype: ratsept
> > +372 5532260
> 
> ## 
> 
> Tiit Rätsep
> Wazombi Labs OÜ
> skype: ratsept
> +372 5532260

## 

Tiit Rätsep
Wazombi Labs OÜ
skype: ratsept
+372 5532260

**Comment by jmoyerman** [comment]
Would you mind shooting me an email? joshua.moyerman@stellascapes.com (Or I can shoot you one?)

**Pull request merged**
